# Generated by Django 5.2.4 on 2025-08-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_query_output_delete_answer_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='output',
            field=models.CharField(max_length=40000),
        ),
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.CharField(max_length=40000),
        ),
    ]
