# Generated by Django 5.2.4 on 2025-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_output_output_alter_query_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
