# Generated by Django 5.2.4 on 2025-08-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_query_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='amount',
        ),
    ]
