# Generated by Django 5.2.4 on 2025-08-01 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_query_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
