# Generated by Django 5.2.4 on 2025-08-03 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_query_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSAEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=1000)),
                ('solution', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='PSAGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
            ],
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_solution', models.CharField(max_length=40000)),
                ('ai_answer', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('psa_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psaentry')),
            ],
        ),
        migrations.AddField(
            model_name='psaentry',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.psagroup'),
        ),
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
