# Generated by Django 5.2.4 on 2025-08-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_psaentry_psagroup_airesponse_psaentry_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psagroup',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
