# Generated by Django 5.2.4 on 2025-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_competition_user_alter_psagroup_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='short_description',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
