# Generated by Django 5.2.4 on 2025-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_competition_user_competition_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='num_questions',
            field=models.IntegerField(default=1),
        ),
    ]
